name: CI

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git
      - name: Install GoReleaser
        if: steps.semantic_release.outputs.new_release_published == 'true'
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - name: Publish release
        if: steps.semantic_release.outputs.new_release_published == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ steps.semantic_release.outputs.notes }}" > /tmp/release-notes.md
          echo "== Release notes =="
          cat /tmp/release-notes.md
          echo "==   End notes   =="
          goreleaser release --release-notes /tmp/release-notes.md --clean
